/**
 * Document Config Loader
 * 
 * Loads document-level configuration from config.json files sibling to spec entries.
 * Provides fallback ID generation when config is not present.
 */

import type { FileProvider } from '#src/file-provider/types';
import { isFileNotFoundError } from '#src/file-provider/types';
import type { DocumentConfig, ResolvedDocumentConfig } from './types.js';

/**
 * Generate an auto ID from entry path
 * 
 * Pattern: <parent-folder-name>-<file-name> (without extension)
 * Example: /spec/workspace/pkg-a/index.html → pkg-a-index
 */
export function generateIdFromPath(entryPath: string): string {
    // Normalize path separators
    const normalizedPath = entryPath.replace(/\\/g, '/');
    const parts = normalizedPath.split('/').filter(p => p.length > 0);

    if (parts.length === 0) {
        return 'unknown';
    }

    // Get filename without extension
    const filename = parts[parts.length - 1];
    const filenameWithoutExt = filename.replace(/\.[^.]+$/, '');

    // Get parent folder name (if exists)
    if (parts.length >= 2) {
        const parentFolder = parts[parts.length - 2];
        return `${parentFolder}`;
    }

    return filenameWithoutExt;
}

/**
 * Get the config.json path sibling to an entry file
 */
export function getConfigPath(entryPath: string): string {
    // Replace the filename with config.json
    const normalizedPath = entryPath.replace(/\\/g, '/');
    const lastSlash = normalizedPath.lastIndexOf('/');

    if (lastSlash === -1) {
        return 'config.json';
    }

    return normalizedPath.substring(0, lastSlash + 1) + 'config.json';
}

/**
 * Load document configuration from config.json sibling to entry
 * 
 * If config.json doesn't exist, returns a resolved config with auto-generated ID.
 * 
 * @param fileProvider - File provider to read from
 * @param entryPath - Path to the spec entry file (e.g., index.html)
 * @returns Resolved config with ID and dependencies
 */
export async function loadDocConfig(
    fileProvider: FileProvider,
    entryPath: string
): Promise<ResolvedDocumentConfig> {
    const configPath = getConfigPath(entryPath);
    const canonicalPath = fileProvider.canonicalize(configPath);

    try {
        const content = await fileProvider.readText(canonicalPath);
        const config = JSON.parse(content) as DocumentConfig;

        // Determine ID (use provided or auto-generate)
        const hasValidId = config.id && typeof config.id === 'string';
        const id = hasValidId ? config.id as string : generateIdFromPath(entryPath);

        return {
            ...config,
            id,
            deps: Array.isArray(config.deps) ? config.deps : [],
            autoGenerated: !hasValidId,
        };
    } catch (error) {
        if (isFileNotFoundError(error)) {
            // Config doesn't exist - auto-generate ID
            return {
                id: generateIdFromPath(entryPath),
                deps: [],
                autoGenerated: true,
            };
        }

        // JSON parse error or other read error - fall back to auto-generated
        return {
            id: generateIdFromPath(entryPath),
            deps: [],
            autoGenerated: true,
        };
    }
}
