/**
 * Document Config Types
 * 
 * Types for document-level configuration (config.json).
 * Used to define document IDs, dependencies, and optional respec configuration.
 */

export type DocumentId = string;
export type ISODateString = `${number}-${number}-${number}`;
export type MaturityLevel = 'incubating' | 'draft' | 'prerelease' | 'stable';
import { PersonEntry } from "#src/preprocess/types";

/**
 * Raw Bikeshed configuration as embedded in config.json
 */
export interface RawBikeshedConfig {
    title?: string;
    shortname?: string;
    status?: string;
    level?: number | string;
    group?: string;
    ed?: string;
    tr?: string;
    created?: string;
    modified?: string;
    repository?: string;
    maxtocdepth?: number | string;
    editor?: PersonEntry[];
    formereditor?:PersonEntry[];
    abstract?: string;
    boilerplate?: string;
    testsuite?: string;
    [key: string]: unknown;
}



/**
 * Raw ReSpec configuration as embedded in config.json
 */
export interface RawRespecConfig {
    // Document metadata
    title?: string;
    shortName?: string;
    subtitle?: string;

    // Status and versioning
    specStatus?: string;
    version?: string;
    publishDate?: string;
    creationDate?: string;
    modificationDate?: string;
    thisVersion?: string;
    latestVersion?: string;
    prevVersion?: string;

    // People
    editors?: PersonEntry[];
    authors?: PersonEntry[];

    // Content
    abstract?: string;

    // Legal
    license?: string;
    copyright?: string;

    // Branding
    logos?: Array<{ src: string; alt?: string; href?: string; url?: string }>;

    // Organization
    group?: string | { name: string; url?: string };
    repository?: string | { url: string; branch?: string; type?: 'github' | 'gitlab' | 'manual' };

    // Structure
    noTOC?: boolean;
    maxTocLevel?: number;

    // Bibliography
    localBiblio?: Record<string, unknown>;

    // Cross-references
    xref?: string | string[] | Record<string, string>;
}

export interface ResolvedDocumentConfig {
  /** Document ID (from config or auto-generated) */
  id: DocumentId;

  /** Dependencies (empty array if none) */
  deps: DocumentId[];

  /** Document title (core config setting, takes priority over respec.title) */
  title?: string;

  /** Last update date (core config setting, takes priority over respec.modificationDate) */
  lastUpdateDate?: ISODateString;

  /** Repository URL or descriptor (core config setting, takes priority over respec.repository) */
  repository?: string | { url: string; branch?: string; type?: 'github' | 'gitlab' | 'manual' };

  /** Maturity level (core config setting, takes priority over mapped respec.specStatus) */
  maturityLevel?: MaturityLevel;

  /** Base URL for assembling thisVersion when not explicitly set */
  baseUrl?: string;

  /** Optional ReSpec configuration embedded in config.json */
  respec?: RawRespecConfig;

  /** Optional Bikeshed configuration embedded in config.json */
  bikeshed?: RawBikeshedConfig;

  /** 
   * Custom user-defined properties. 
   * Highest priority - overwrites both root and respec values.
   */
  custom?: Record<string, unknown>;

  /** Whether the ID was auto-generated */
  autoGenerated: boolean;
}

/**
 * Raw config as read from config.json:
 * - id and deps are optional
 * - autoGenerated should not be user-provided, so we remove it
 */
export type DocumentConfig =
  Omit<Partial<ResolvedDocumentConfig>, 'autoGenerated'>;
