/**
 * Document Config Types
 * 
 * Types for document-level configuration (config.json).
 * Used to define document IDs, dependencies, and optional respec configuration.
 */

import type { RawRespecConfig } from './loader.js';

/**
 * Document configuration schema
 * 
 * Located in config.json sibling to spec entry files.
 */
export interface DocumentConfig {
    /** Unique document identifier within the workspace */
    id?: string;

    /** 
     * Array of document IDs this document depends on.
     * Dependencies are processed before this document.
     */
    deps?: string[];

    /**
     * Last update date (core config setting, takes priority over respec.modificationDate)
     */
    lastUpdateDate?: string;

    /**
     * Optional ReSpec configuration embedded in config.json.
     * If present, this replaces the need for a separate config.respec.json file.
     */
    respec?: RawRespecConfig;
}

/**
 * Resolved document config with guaranteed fields
 */
export interface ResolvedDocumentConfig {
    /** Document ID (from config or auto-generated) */
    id: string;

    /** Dependencies (empty array if none) */
    deps: string[];

    /** Whether the ID was auto-generated */
    autoGenerated: boolean;

    /** Root-level lastUpdateDate (takes priority over respec.modificationDate) */
    lastUpdateDate?: string;

    /** Optional respec configuration if present in config.json */
    respec?: RawRespecConfig;
}
